# An example of pushing XML events generated by the low-level expat
# XML library into coroutines

import xml.parsers.expat
from buses import *


def expat_parse(f, target):
    parser = xml.parsers.expat.ParserCreate()
    parser.buffer_size = 65536
    parser.buffer_text = True

    parser.StartElementHandler = \
        lambda name,atrrs: target.send(("start", (name,atrrs)))

    parser.EndElementHandler = \
        lambda name: target.send(("end", name))

    parser.CharacterDataHandler = \
        lambda data: target.send(("text", data))

    parser.ParseFile(f,)


if __name__ == "__main__":
    with open("allroutes.xml", "rb") as f:
        expat_parse(f,
                    buses_to_dicts(
                        filter_on_field("route", "22",filter_on_field(
                            "direction", "North Bound", bus_locations()
                        ))
                    ))